version: "3"

services:
    sw6_deepl:
      image: dockware/dev:6.6.7.1
      container_name: sw6_dev
      ports:
         - "80:80"
         - "3306:3306"
         - "22:22"
         - "9888:8888"
         - "9999:9999"
         - "9998:9998"
      networks:
         - web
      volumes:
         - "../LsSkeleton/:/var/www/html/custom/plugins/LsSkeleton/"
      environment:
         - XDEBUG_ENABLED=1

networks:
  web:
    external: false